#!/usr/bin/perl

use Failint::Checks::Log;
use Failint::Checks::Vars;

if (not -d $class_dir)  {
    error("", "","no 'class' subdir in fai config space");
} elsif ( not glob($class_dir . "/*")) {
    error("", "", "class directory does not contain any files");
}

if (not -d $package_config_dir)  {
    error("", "","no 'package_config' subdir in fai config space");
} elsif ( not glob($package_config_dir . "/*")) {
    error("", "", "package_config directory does not contain any files");
}

if (not -d $debconf_dir)  {
    error("", "","no 'debconf' subdir in fai config space");
} elsif ( not glob($debconf_dir . "/*")) {
    warning("", "", "debconf directory does not contain any files");
}

if (not -d $disk_config_dir)  {
    error("", "","no 'disk_config' subdir in fai config space");
} elsif ( not glob($disk_config_dir . "/*")) {
    error("", "", "disk_config directory does not contain any files");
}

if (not -d $debconf_dir)  {
    error("", "","no 'debconf' subdir in fai config space");
} elsif ( not glob($debconf_dir . "/*")) {
    warning("", "", "debconf directory does not contain any files");
}

if (not -d $files_dir)  {
    error("", "","no 'files' subdir in fai config space");
} elsif ( not glob($files_dir . "/*")) {
    warning("", "", "files directory does not contain any files");
}

if (not -d $hooks_dir)  {
    error("", "","no 'hooks' subdir in fai config space");
} elsif ( not glob($hooks_dir . "/*")) {
    warning("", "", "hooks directory does not contain any hooks");
}

if (not -d $scripts_dir)  {
    error("", "","no 'scripts' subdir in fai config space");
} elsif ( not glob($scripts_dir . "/*")) {
    warning("", "", "scripts directory does not contain any hooks");
}

